// backend/seed.js
const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const Mcq = require('./models/Mcq');
const CodingProblem = require('./models/CodingProblem');
const InterviewQuestion = require('./models/InterviewQuestion');

const mcqData = [
   { question: 'Primary key in DBMS is?', options: ['a) Unique and not null', 'b) Can be null', 'c) Duplicates allowed'], correctAnswer: 'a) Unique and not null', explanation: 'Primary key uniquely identifies each record.', companyTag: '' },
  { question: 'Which data structure uses FIFO?', options: ['a) Stack', 'b) Queue', 'c) Tree'], correctAnswer: 'b) Queue', explanation: 'Queue works on First In First Out principle.', companyTag: '' },
  { question: 'Which SQL command is used to extract data?', options: ['a) INSERT', 'b) SELECT', 'c) UPDATE'], correctAnswer: 'b) SELECT', explanation: 'SELECT is used to fetch records.', companyTag: '' },
  { question: 'Which sorting algorithm has best average case?', options: ['a) Bubble Sort', 'b) Merge Sort', 'c) Insertion Sort'], correctAnswer: 'b) Merge Sort', explanation: 'Merge Sort average case is O(n log n).', companyTag: '' },
  { question: 'Time complexity of binary search is?', options: ['a) O(n)', 'b) O(log n)', 'c) O(n log n)'], correctAnswer: 'b) O(log n)', explanation: 'Binary search works by dividing the array in half each step.', companyTag: '' },
  { question: 'In OS, semaphore is used for?', options: ['a) Synchronization', 'b) Scheduling', 'c) Deadlock'], correctAnswer: 'a) Synchronization', explanation: 'Semaphore helps in process synchronization.', companyTag: '' },
  { question: 'Which operator is used to allocate memory dynamically in C++?', options: ['a) malloc', 'b) new', 'c) alloc'], correctAnswer: 'b) new', explanation: 'new operator is used for dynamic allocation in C++.', companyTag: '' },
  { question: 'What does ACID stand for in databases?', options: ['a) Atomicity, Consistency, Isolation, Durability', 'b) Accuracy, Clarity, Integrity, Durability', 'c) None'], correctAnswer: 'a) Atomicity, Consistency, Isolation, Durability', explanation: 'ACID ensures reliable DB transactions.', companyTag: '' },
  { question: 'Which pointer is automatically passed to non-static member functions in C++?', options: ['a) this', 'b) super', 'c) self'], correctAnswer: 'a) this', explanation: 'this pointer points to current object.', companyTag: '' },
  { question: 'Which OS is open source?', options: ['a) Windows', 'b) Linux', 'c) MacOS'], correctAnswer: 'b) Linux', explanation: 'Linux is an open source operating system.', companyTag: '' },
  { question: 'Which keyword is used to handle exceptions in Java?', options: ['a) catch', 'b) throw', 'c) try'], correctAnswer: 'c) try', explanation: 'try block is used to enclose code that may throw an exception.', companyTag: '' },
  { question: 'In C language, what happens if you access array out of bound?', options: ['a) Compilation error', 'b) Runtime error', 'c) Undefined behavior'], correctAnswer: 'c) Undefined behavior', explanation: 'Array out of bounds in C results in undefined behavior.', companyTag: '' },
  { question: 'Which protocol is used for secure communication over HTTP?', options: ['a) FTP', 'b) HTTPS', 'c) SMTP'], correctAnswer: 'b) HTTPS', explanation: 'HTTPS uses SSL/TLS for secure communication.', companyTag: '' },
  { question: 'Which of these is not a relational DBMS?', options: ['a) MySQL', 'b) MongoDB', 'c) Oracle'], correctAnswer: 'b) MongoDB', explanation: 'MongoDB is NoSQL document database.', companyTag: '' },
  { question: 'Which scheduling algorithm gives minimum average waiting time?', options: ['a) FCFS', 'b) SJF', 'c) Round Robin'], correctAnswer: 'b) SJF', explanation: 'Shortest Job First gives minimum average waiting time.', companyTag: '' },
  { question: 'Which memory is fastest?', options: ['a) Cache', 'b) RAM', 'c) Hard Disk'], correctAnswer: 'a) Cache', explanation: 'Cache memory is closest to CPU and fastest.', companyTag: '' },
  { question: 'What is DBMS?', options: ['a) Data Base Management System', 'b) Data Backup Management Service', 'c) Disk Based Memory System'], correctAnswer: 'a) Data Base Management System', explanation: 'DBMS is software to manage and organize databases.', companyTag: '' },
  { question: 'OSI model has how many layers?', options: ['a) 5', 'b) 6', 'c) 7'], correctAnswer: 'c) 7', explanation: 'OSI has 7 layers from Physical to Application.', companyTag: '' },
  { question: 'Which of the following is NOT an OOP principle?', options: ['a) Encapsulation', 'b) Abstraction', 'c) Compilation'], correctAnswer: 'c) Compilation', explanation: 'OOP principles are Encapsulation, Abstraction, Inheritance, Polymorphism.', companyTag: '' },
  { question: 'Which one is a client-side scripting language?', options: ['a) PHP', 'b) JavaScript', 'c) Python'], correctAnswer: 'b) JavaScript', explanation: 'JavaScript runs on client side.', companyTag: '' },
  { question: 'If a train runs 60 km in 1 hour, what is its speed in m/s?', options: ['a) 12', 'b) 16.67', 'c) 18'], correctAnswer: 'b) 16.67', explanation: '60 km/h = (60 * 1000) / 3600 = 16.67 m/s.', companyTag: '' },
  { question: 'In OS, thrashing occurs due to?', options: ['a) Excessive paging', 'b) Deadlock', 'c) Cache miss'], correctAnswer: 'a) Excessive paging', explanation: 'Thrashing happens when CPU spends more time swapping pages.', companyTag: '' },
  { question: 'Which SQL command is used to remove a table?', options: ['a) DROP', 'b) DELETE', 'c) REMOVE'], correctAnswer: 'a) DROP', explanation: 'DROP is used to remove the table structure and data.', companyTag: '' },
  { question: 'Which protocol is used to send emails?', options: ['a) SMTP', 'b) FTP', 'c) HTTP'], correctAnswer: 'a) SMTP', explanation: 'Simple Mail Transfer Protocol is used to send emails.', companyTag: '' },
  { question: 'Which layer of OSI handles routing?', options: ['a) Transport', 'b) Network', 'c) Data Link'], correctAnswer: 'b) Network', explanation: 'Network layer is responsible for routing.', companyTag: '' },
  { question: 'Which searching algorithm is best for linked lists?', options: ['a) Binary Search', 'b) Linear Search', 'c) Hashing'], correctAnswer: 'b) Linear Search', explanation: 'Binary search needs random access, so linear is used.', companyTag: '' },
  { question: 'Deadlock occurs when?', options: ['a) Processes are waiting for each other', 'b) CPU is idle', 'c) Memory is full'], correctAnswer: 'a) Processes are waiting for each other', explanation: 'Deadlock happens when two or more processes wait indefinitely for resources.', companyTag: '' },
  { question: 'Which is a non-linear data structure?', options: ['a) Array', 'b) Linked List', 'c) Tree'], correctAnswer: 'c) Tree', explanation: 'Tree and graphs are non-linear.', companyTag: '' },
  { question: 'Which type of memory is volatile?', options: ['a) ROM', 'b) RAM', 'c) Hard Disk'], correctAnswer: 'b) RAM', explanation: 'RAM loses data when power is turned off.', companyTag: '' },
  { question: 'In Java, which collection does not allow duplicate elements?', options: ['a) List', 'b) Set', 'c) Map'], correctAnswer: 'b) Set', explanation: 'Set does not allow duplicates.', companyTag: '' },
  { question: 'Which OS is open source?', options: ['a) Windows', 'b) Linux', 'c) MacOS'], correctAnswer: 'b) Linux', explanation: 'Linux is an open source operating system.', companyTag: 'TCS' },
  { question: 'In OS, semaphore is used for?', options: ['a) Synchronization', 'b) Scheduling', 'c) Deadlock'], correctAnswer: 'a) Synchronization', explanation: 'Semaphore helps in process synchronization.', companyTag: 'TCS' },
  { question: 'Which protocol is used to send emails?', options: ['a) SMTP', 'b) FTP', 'c) HTTP'], correctAnswer: 'a) SMTP', explanation: 'Simple Mail Transfer Protocol is used to send emails.', companyTag: 'TCS' },
  { question: 'Which one is a client-side scripting language?', options: ['a) PHP', 'b) JavaScript', 'c) Python'], correctAnswer: 'b) JavaScript', explanation: 'JavaScript runs on client side.', companyTag: 'TCS' },
  { question: 'Which searching algorithm is best for linked lists?', options: ['a) Binary Search', 'b) Linear Search', 'c) Hashing'], correctAnswer: 'b) Linear Search', explanation: 'Binary search needs random access, so linear is used.', companyTag: 'TCS' },
  { question: 'Which scheduling algorithm gives minimum average waiting time?', options: ['a) FCFS', 'b) SJF', 'c) Round Robin'], correctAnswer: 'b) SJF', explanation: 'Shortest Job First gives minimum average waiting time.', companyTag: 'TCS' },
  { question: 'In Java, which collection does not allow duplicate elements?', options: ['a) List', 'b) Set', 'c) Map'], correctAnswer: 'b) Set', explanation: 'Set does not allow duplicates.', companyTag: 'TCS' },
  { question: 'Which sorting algorithm has best average case?', options: ['a) Bubble Sort', 'b) Merge Sort', 'c) Insertion Sort'], correctAnswer: 'b) Merge Sort', explanation: 'Merge Sort average case is O(n log n).', companyTag: 'TCS' },
  { question: 'Which protocol is used for secure communication over HTTP?', options: ['a) FTP', 'b) HTTPS', 'c) SMTP'], correctAnswer: 'b) HTTPS', explanation: 'HTTPS uses SSL/TLS for secure communication.', companyTag: 'TCS' },
  { question: 'What does ACID stand for in databases?', options: ['a) Atomicity, Consistency, Isolation, Durability', 'b) Accuracy, Clarity, Integrity, Durability', 'c) None'], correctAnswer: 'a) Atomicity, Consistency, Isolation, Durability', explanation: 'ACID ensures reliable DB transactions.', companyTag: 'TCS' },
  { question: 'Which pointer is automatically passed to non-static member functions in C++?', options: ['a) this', 'b) super', 'c) self'], correctAnswer: 'a) this', explanation: 'this pointer points to current object.', companyTag: 'TCS' },
  { question: 'In C language, what happens if you access array out of bound?', options: ['a) Compilation error', 'b) Runtime error', 'c) Undefined behavior'], correctAnswer: 'c) Undefined behavior', explanation: 'Array out of bounds in C results in undefined behavior.', companyTag: 'TCS' },
  { question: 'Which of these is not a relational DBMS?', options: ['a) MySQL', 'b) MongoDB', 'c) Oracle'], correctAnswer: 'b) MongoDB', explanation: 'MongoDB is NoSQL document database.', companyTag: 'TCS' },
  { question: 'What is DBMS?', options: ['a) Data Base Management System', 'b) Data Backup Management Service', 'c) Disk Based Memory System'], correctAnswer: 'a) Data Base Management System', explanation: 'DBMS is software to manage and organize databases.', companyTag: 'TCS' },
  { question: 'Which data structure uses FIFO?', options: ['a) Stack', 'b) Queue', 'c) Tree'], correctAnswer: 'b) Queue', explanation: 'Queue works on First In First Out principle.', companyTag: 'TCS' },
  { question: 'Which type of memory is volatile?', options: ['a) ROM', 'b) RAM', 'c) Hard Disk'], correctAnswer: 'b) RAM', explanation: 'RAM loses data when power is turned off.', companyTag: 'TCS' },
  { question: 'Deadlock occurs when?', options: ['a) Processes are waiting for each other', 'b) CPU is idle', 'c) Memory is full'], correctAnswer: 'a) Processes are waiting for each other', explanation: 'Deadlock happens when two or more processes wait indefinitely for resources.', companyTag: 'Infosys' },
  { question: 'Which SQL command is used to remove a table?', options: ['a) DROP', 'b) DELETE', 'c) REMOVE'], correctAnswer: 'a) DROP', explanation: 'DROP is used to remove the table structure and data.', companyTag: 'Infosys' },
  { question: 'Primary key in DBMS is?', options: ['a) Unique and not null', 'b) Can be null', 'c) Duplicates allowed'], correctAnswer: 'a) Unique and not null', explanation: 'Primary key uniquely identifies each record.', companyTag: 'Infosys' },
  { question: 'Time complexity of binary search is?', options: ['a) O(n)', 'b) O(log n)', 'c) O(n log n)'], correctAnswer: 'b) O(log n)', explanation: 'Binary search works by dividing the array in half each step.', companyTag: 'Infosys' },
  { question: 'Which of these is not a relational DBMS?', options: ['a) MySQL', 'b) MongoDB', 'c) Oracle'], correctAnswer: 'b) MongoDB', explanation: 'MongoDB is NoSQL document database.', companyTag: 'Infosys' },
  { question: 'Which protocol is used for secure communication over HTTP?', options: ['a) FTP', 'b) HTTPS', 'c) SMTP'], correctAnswer: 'b) HTTPS', explanation: 'HTTPS uses SSL/TLS for secure communication.', companyTag: 'Infosys' },
  { question: 'Which OS is open source?', options: ['a) Windows', 'b) Linux', 'c) MacOS'], correctAnswer: 'b) Linux', explanation: 'Linux is an open source operating system.', companyTag: 'Infosys' },
  { question: 'Which layer of OSI handles routing?', options: ['a) Transport', 'b) Network', 'c) Data Link'], correctAnswer: 'b) Network', explanation: 'Network layer is responsible for routing.', companyTag: 'Infosys' },
  { question: 'In OS, thrashing occurs due to?', options: ['a) Excessive paging', 'b) Deadlock', 'c) Cache miss'], correctAnswer: 'a) Excessive paging', explanation: 'Thrashing happens when CPU spends more time swapping pages.', companyTag: 'Infosys' },
  { question: 'Which of the following is NOT an OOP principle?', options: ['a) Encapsulation', 'b) Abstraction', 'c) Compilation'], correctAnswer: 'c) Compilation', explanation: 'OOP principles are Encapsulation, Abstraction, Inheritance, Polymorphism.', companyTag: 'Infosys' },
  { question: 'OSI model has how many layers?', options: ['a) 5', 'b) 6', 'c) 7'], correctAnswer: 'c) 7', explanation: 'OSI has 7 layers from Physical to Application.', companyTag: 'Infosys' },
  { question: 'What does ACID stand for in databases?', options: ['a) Atomicity, Consistency, Isolation, Durability', 'b) Accuracy, Clarity, Integrity, Durability', 'c) None'], correctAnswer: 'a) Atomicity, Consistency, Isolation, Durability', explanation: 'ACID ensures reliable DB transactions.', companyTag: 'Infosys' },
  { question: 'Which type of memory is volatile?', options: ['a) ROM', 'b) RAM', 'c) Hard Disk'], correctAnswer: 'b) RAM', explanation: 'RAM loses data when power is turned off.', companyTag: 'Infosys' },
  { question: 'Which one is a client-side scripting language?', options: ['a) PHP', 'b) JavaScript', 'c) Python'], correctAnswer: 'b) JavaScript', explanation: 'JavaScript runs on client side.', companyTag: 'Infosys' },
  { question: 'Which is a non-linear data structure?', options: ['a) Array', 'b) Linked List', 'c) Tree'], correctAnswer: 'c) Tree', explanation: 'Tree and graphs are non-linear.', companyTag: 'Infosys' },
  { question: 'Which memory is fastest?', options: ['a) Cache', 'b) RAM', 'c) Hard Disk'], correctAnswer: 'a) Cache', explanation: 'Cache memory is closest to CPU and fastest.', companyTag: 'Infosys' },
  { question: 'In OS, semaphore is used for?', options: ['a) Synchronization', 'b) Scheduling', 'c) Deadlock'], correctAnswer: 'a) Synchronization', explanation: 'Semaphore helps in process synchronization.', companyTag: 'Infosys' },
  { question: 'Which protocol is used to send emails?', options: ['a) SMTP', 'b) FTP', 'c) HTTP'], correctAnswer: 'a) SMTP', explanation: 'Simple Mail Transfer Protocol is used to send emails.', companyTag: 'Infosys' },
  { question: 'In Java, which collection does not allow duplicate elements?', options: ['a) List', 'b) Set', 'c) Map'], correctAnswer: 'b) Set', explanation: 'Set does not allow duplicates.', companyTag: 'Infosys' },
  { question: 'Which sorting algorithm has best average case?', options: ['a) Bubble Sort', 'b) Merge Sort', 'c) Insertion Sort'], correctAnswer: 'b) Merge Sort', explanation: 'Merge Sort average case is O(n log n).', companyTag: 'Infosys' },
  { question: 'Which layer of OSI handles routing?', options: ['a) Transport', 'b) Network', 'c) Data Link'], correctAnswer: 'b) Network', explanation: 'Network layer is responsible for routing.', companyTag: 'Wipro' },
  { question: 'Which SQL command is used to remove a table?', options: ['a) DROP', 'b) DELETE', 'c) REMOVE'], correctAnswer: 'a) DROP', explanation: 'DROP is used to remove the table structure and data.', companyTag: 'Wipro' },
  { question: 'Which of the following is NOT an OOP principle?', options: ['a) Encapsulation', 'b) Abstraction', 'c) Compilation'], correctAnswer: 'c) Compilation', explanation: 'OOP principles are Encapsulation, Abstraction, Inheritance, Polymorphism.', companyTag: 'Wipro' },
  { question: 'Which data structure uses FIFO?', options: ['a) Stack', 'b) Queue', 'c) Tree'], correctAnswer: 'b) Queue', explanation: 'Queue works on First In First Out principle.', companyTag: 'Wipro' },
  { question: 'What does ACID stand for in databases?', options: ['a) Atomicity, Consistency, Isolation, Durability', 'b) Accuracy, Clarity, Integrity, Durability', 'c) None'], correctAnswer: 'a) Atomicity, Consistency, Isolation, Durability', explanation: 'ACID ensures reliable DB transactions.', companyTag: 'Wipro' },
  { question: 'Which one is a client-side scripting language?', options: ['a) PHP', 'b) JavaScript', 'c) Python'], correctAnswer: 'b) JavaScript', explanation: 'JavaScript runs on client side.', companyTag: 'Wipro' },
  { question: 'Which scheduling algorithm gives minimum average waiting time?', options: ['a) FCFS', 'b) SJF', 'c) Round Robin'], correctAnswer: 'b) SJF', explanation: 'Shortest Job First gives minimum average waiting time.', companyTag: 'Wipro' },
  { question: 'Which protocol is used to send emails?', options: ['a) SMTP', 'b) FTP', 'c) HTTP'], correctAnswer: 'a) SMTP', explanation: 'Simple Mail Transfer Protocol is used to send emails.', companyTag: 'Wipro' },
  { question: 'Time complexity of binary search is?', options: ['a) O(n)', 'b) O(log n)', 'c) O(n log n)'], correctAnswer: 'b) O(log n)', explanation: 'Binary search works by dividing the array in half each step.', companyTag: 'Wipro' },
  { question: 'Which operator is used to allocate memory dynamically in C++?', options: ['a) malloc', 'b) new', 'c) alloc'], correctAnswer: 'b) new', explanation: 'new operator is used for dynamic allocation in C++.', companyTag: 'Wipro' },
  { question: 'OSI model has how many layers?', options: ['a) 5', 'b) 6', 'c) 7'], correctAnswer: 'c) 7', explanation: 'OSI has 7 layers from Physical to Application.', companyTag: 'Wipro' },
  { question: 'In OS, thrashing occurs due to?', options: ['a) Excessive paging', 'b) Deadlock', 'c) Cache miss'], correctAnswer: 'a) Excessive paging', explanation: 'Thrashing happens when CPU spends more time swapping pages.', companyTag: 'Wipro' },
  { question: 'Which SQL command is used to extract data?', options: ['a) INSERT', 'b) SELECT', 'c) UPDATE'], correctAnswer: 'b) SELECT', explanation: 'SELECT is used to fetch records.', companyTag: 'Wipro' },
  { question: 'Which is a non-linear data structure?', options: ['a) Array', 'b) Linked List', 'c) Tree'], correctAnswer: 'c) Tree', explanation: 'Tree and graphs are non-linear.', companyTag: 'Wipro' },
  { question: 'In OS, semaphore is used for?', options: ['a) Synchronization', 'b) Scheduling', 'c) Deadlock'], correctAnswer: 'a) Synchronization', explanation: 'Semaphore helps in process synchronization.', companyTag: 'Wipro' },
  { question: 'In Java, which collection does not allow duplicate elements?', options: ['a) List', 'b) Set', 'c) Map'], correctAnswer: 'b) Set', explanation: 'Set does not allow duplicates.', companyTag: 'Wipro' },
  { question: 'In C language, what happens if you access array out of bound?', options: ['a) Compilation error', 'b) Runtime error', 'c) Undefined behavior'], correctAnswer: 'c) Undefined behavior', explanation: 'Array out of bounds in C results in undefined behavior.', companyTag: 'Cognizant' },
  { question: 'Which memory is fastest?', options: ['a) Cache', 'b) RAM', 'c) Hard Disk'], correctAnswer: 'a) Cache', explanation: 'Cache memory is closest to CPU and fastest.', companyTag: 'Cognizant' },
  { question: 'Primary key in DBMS is?', options: ['a) Unique and not null', 'b) Can be null', 'c) Duplicates allowed'], correctAnswer: 'a) Unique and not null', explanation: 'Primary key uniquely identifies each record.', companyTag: 'Cognizant' },
  { question: 'Which keyword is used to handle exceptions in Java?', options: ['a) catch', 'b) throw', 'c) try'], correctAnswer: 'c) try', explanation: 'try block is used to enclose code that may throw an exception.', companyTag: 'Cognizant' },
  { question: 'Which type of memory is volatile?', options: ['a) ROM', 'b) RAM', 'c) Hard Disk'], correctAnswer: 'b) RAM', explanation: 'RAM loses data when power is turned off.', companyTag: 'Cognizant' },
  { question: 'Which of these is not a relational DBMS?', options: ['a) MySQL', 'b) MongoDB', 'c) Oracle'], correctAnswer: 'b) MongoDB', explanation: 'MongoDB is NoSQL document database.', companyTag: 'Cognizant' },
  { question: 'Which pointer is automatically passed to non-static member functions in C++?', options: ['a) this', 'b) super', 'c) self'], correctAnswer: 'a) this', explanation: 'this pointer points to current object.', companyTag: 'Cognizant' },
  { question: 'Which operator is used to allocate memory dynamically in C++?', options: ['a) malloc', 'b) new', 'c) alloc'], correctAnswer: 'b) new', explanation: 'new operator is used for dynamic allocation in C++.', companyTag: 'Cognizant' },
  { question: 'Which is a non-linear data structure?', options: ['a) Array', 'b) Linked List', 'c) Tree'], correctAnswer: 'c) Tree', explanation: 'Tree and graphs are non-linear.', companyTag: 'Cognizant' },
  { question: 'Which OS is open source?', options: ['a) Windows', 'b) Linux', 'c) MacOS'], correctAnswer: 'b) Linux', explanation: 'Linux is an open source operating system.', companyTag: 'Cognizant' },
  { question: 'Which SQL command is used to extract data?', options: ['a) INSERT', 'b) SELECT', 'c) UPDATE'], correctAnswer: 'b) SELECT', explanation: 'SELECT is used to fetch records.', companyTag: 'Cognizant' },
  { question: 'Which SQL command is used to remove a table?', options: ['a) DROP', 'b) DELETE', 'c) REMOVE'], correctAnswer: 'a) DROP', explanation: 'DROP is used to remove the table structure and data.', companyTag: 'Cognizant' },
  { question: 'Deadlock occurs when?', options: ['a) Processes are waiting for each other', 'b) CPU is idle', 'c) Memory is full'], correctAnswer: 'a) Processes are waiting for each other', explanation: 'Deadlock happens when two or more processes wait indefinitely for resources.', companyTag: 'Cognizant' },
  { question: 'Time complexity of binary search is?', options: ['a) O(n)', 'b) O(log n)', 'c) O(n log n)'], correctAnswer: 'b) O(log n)', explanation: 'Binary search works by dividing the array in half each step.', companyTag: 'Cognizant' },
  { question: 'In OS, semaphore is used for?', options: ['a) Synchronization', 'b) Scheduling', 'c) Deadlock'], correctAnswer: 'a) Synchronization', explanation: 'Semaphore helps in process synchronization.', companyTag: 'Cognizant' },
  { question: 'Which data structure uses FIFO?', options: ['a) Stack', 'b) Queue', 'c) Tree'], correctAnswer: 'b) Queue', explanation: 'Queue works on First In First Out principle.', companyTag: 'Cognizant' },
  { question: 'OSI model has how many layers?', options: ['a) 5', 'b) 6', 'c) 7'], correctAnswer: 'c) 7', explanation: 'OSI has 7 layers from Physical to Application.', companyTag: 'Cognizant' },
  { question: 'Which protocol is used for secure communication over HTTP?', options: ['a) FTP', 'b) HTTPS', 'c) SMTP'], correctAnswer: 'b) HTTPS', explanation: 'HTTPS uses SSL/TLS for secure communication.', companyTag: 'Cognizant' },
  { question: 'Which protocol is used to send emails?', options: ['a) SMTP', 'b) FTP', 'c) HTTP'], correctAnswer: 'a) SMTP', explanation: 'Simple Mail Transfer Protocol is used to send emails.', companyTag: 'Cognizant' },
  { question: 'Which protocol is used to send emails?', options: ['a) SMTP', 'b) FTP', 'c) HTTP'], correctAnswer: 'a) SMTP', explanation: 'Simple Mail Transfer Protocol is used to send emails.', companyTag: 'IBM' },
  { question: 'Which keyword is used to handle exceptions in Java?', options: ['a) catch', 'b) throw', 'c) try'], correctAnswer: 'c) try', explanation: 'try block is used to enclose code that may throw an exception.', companyTag: 'IBM' },
  { question: 'Which searching algorithm is best for linked lists?', options: ['a) Binary Search', 'b) Linear Search', 'c) Hashing'], correctAnswer: 'b) Linear Search', explanation: 'Binary search needs random access, so linear is used.', companyTag: 'IBM' },
  { question: 'Time complexity of binary search is?', options: ['a) O(n)', 'b) O(log n)', 'c) O(n log n)'], correctAnswer: 'b) O(log n)', explanation: 'Binary search works by dividing the array in half each step.', companyTag: 'IBM' },
  { question: 'Which scheduling algorithm gives minimum average waiting time?', options: ['a) FCFS', 'b) SJF', 'c) Round Robin'], correctAnswer: 'b) SJF', explanation: 'Shortest Job First gives minimum average waiting time.', companyTag: 'IBM' },
  { question: 'Deadlock occurs when?', options: ['a) Processes are waiting for each other', 'b) CPU is idle', 'c) Memory is full'], correctAnswer: 'a) Processes are waiting for each other', explanation: 'Deadlock happens when two or more processes wait indefinitely for resources.', companyTag: 'IBM' },
  { question: 'Which operator is used to allocate memory dynamically in C++?', options: ['a) malloc', 'b) new', 'c) alloc'], correctAnswer: 'b) new', explanation: 'new operator is used for dynamic allocation in C++.', companyTag: 'IBM' },
  { question: 'Which protocol is used for secure communication over HTTP?', options: ['a) FTP', 'b) HTTPS', 'c) SMTP'], correctAnswer: 'b) HTTPS', explanation: 'HTTPS uses SSL/TLS for secure communication.', companyTag: 'IBM' },
  { question: 'Which pointer is automatically passed to non-static member functions in C++?', options: ['a) this', 'b) super', 'c) self'], correctAnswer: 'a) this', explanation: 'this pointer points to current object.', companyTag: 'IBM' },
  { question: 'Which SQL command is used to extract data?', options: ['a) INSERT', 'b) SELECT', 'c) UPDATE'], correctAnswer: 'b) SELECT', explanation: 'SELECT is used to fetch records.', companyTag: 'IBM' },
  { question: 'Which of these is not a relational DBMS?', options: ['a) MySQL', 'b) MongoDB', 'c) Oracle'], correctAnswer: 'b) MongoDB', explanation: 'MongoDB is NoSQL document database.', companyTag: 'IBM' },
  { question: 'If a train runs 60 km in 1 hour, what is its speed in m/s?', options: ['a) 12', 'b) 16.67', 'c) 18'], correctAnswer: 'b) 16.67', explanation: '60 km/h = (60 * 1000) / 3600 = 16.67 m/s.', companyTag: 'IBM' },
  { question: 'Which OS is open source?', options: ['a) Windows', 'b) Linux', 'c) MacOS'], correctAnswer: 'b) Linux', explanation: 'Linux is an open source operating system.', companyTag: 'IBM' },
  { question: 'What is DBMS?', options: ['a) Data Base Management System', 'b) Data Backup Management Service', 'c) Disk Based Memory System'], correctAnswer: 'a) Data Base Management System', explanation: 'DBMS is software to manage and organize databases.', companyTag: 'IBM' },
  { question: 'In C language, what happens if you access array out of bound?', options: ['a) Compilation error', 'b) Runtime error', 'c) Undefined behavior'], correctAnswer: 'c) Undefined behavior', explanation: 'Array out of bounds in C results in undefined behavior.', companyTag: 'IBM' },
  { question: 'If a train runs 60 km in 1 hour, what is its speed in m/s?', options: ['a) 12', 'b) 16.67', 'c) 18'], correctAnswer: 'b) 16.67', explanation: '60 km/h = (60 * 1000) / 3600 = 16.67 m/s.', companyTag: 'Accenture' },
  { question: 'Which sorting algorithm has best average case?', options: ['a) Bubble Sort', 'b) Merge Sort', 'c) Insertion Sort'], correctAnswer: 'b) Merge Sort', explanation: 'Merge Sort average case is O(n log n).', companyTag: 'Accenture' },
  { question: 'Which of the following is NOT an OOP principle?', options: ['a) Encapsulation', 'b) Abstraction', 'c) Compilation'], correctAnswer: 'c) Compilation', explanation: 'OOP principles are Encapsulation, Abstraction, Inheritance, Polymorphism.', companyTag: 'Accenture' },
  { question: 'Which SQL command is used to remove a table?', options: ['a) DROP', 'b) DELETE', 'c) REMOVE'], correctAnswer: 'a) DROP', explanation: 'DROP is used to remove the table structure and data.', companyTag: 'Accenture' },
  { question: 'Primary key in DBMS is?', options: ['a) Unique and not null', 'b) Can be null', 'c) Duplicates allowed'], correctAnswer: 'a) Unique and not null', explanation: 'Primary key uniquely identifies each record.', companyTag: 'Accenture' },
  { question: 'Which scheduling algorithm gives minimum average waiting time?', options: ['a) FCFS', 'b) SJF', 'c) Round Robin'], correctAnswer: 'b) SJF', explanation: 'Shortest Job First gives minimum average waiting time.', companyTag: 'Accenture' },
  { question: 'In C language, what happens if you access array out of bound?', options: ['a) Compilation error', 'b) Runtime error', 'c) Undefined behavior'], correctAnswer: 'c) Undefined behavior', explanation: 'Array out of bounds in C results in undefined behavior.', companyTag: 'Accenture' },
  { question: 'OSI model has how many layers?', options: ['a) 5', 'b) 6', 'c) 7'], correctAnswer: 'c) 7', explanation: 'OSI has 7 layers from Physical to Application.', companyTag: 'Accenture' },
  { question: 'Which keyword is used to handle exceptions in Java?', options: ['a) catch', 'b) throw', 'c) try'], correctAnswer: 'c) try', explanation: 'try block is used to enclose code that may throw an exception.', companyTag: 'Accenture' },
  { question: 'Which data structure uses FIFO?', options: ['a) Stack', 'b) Queue', 'c) Tree'], correctAnswer: 'b) Queue', explanation: 'Queue works on First In First Out principle.', companyTag: 'Accenture' },
  { question: 'Which layer of OSI handles routing?', options: ['a) Transport', 'b) Network', 'c) Data Link'], correctAnswer: 'b) Network', explanation: 'Network layer is responsible for routing.', companyTag: 'Accenture' },
  { question: 'Which protocol is used to send emails?', options: ['a) SMTP', 'b) FTP', 'c) HTTP'], correctAnswer: 'a) SMTP', explanation: 'Simple Mail Transfer Protocol is used to send emails.', companyTag: 'Accenture' },
  { question: 'Which is a non-linear data structure?', options: ['a) Array', 'b) Linked List', 'c) Tree'], correctAnswer: 'c) Tree', explanation: 'Tree and graphs are non-linear.', companyTag: 'Accenture' },
  { question: 'In Java, which collection does not allow duplicate elements?', options: ['a) List', 'b) Set', 'c) Map'], correctAnswer: 'b) Set', explanation: 'Set does not allow duplicates.', companyTag: 'Accenture' },
  { question: 'Deadlock occurs when?', options: ['a) Processes are waiting for each other', 'b) CPU is idle', 'c) Memory is full'], correctAnswer: 'a) Processes are waiting for each other', explanation: 'Deadlock happens when two or more processes wait indefinitely for resources.', companyTag: 'Accenture' },
  { question: 'What is DBMS?', options: ['a) Data Base Management System', 'b) Data Backup Management Service', 'c) Disk Based Memory System'], correctAnswer: 'a) Data Base Management System', explanation: 'DBMS is software to manage and organize databases.', companyTag: 'Accenture' },
  { question: 'Which pointer is automatically passed to non-static member functions in C++?', options: ['a) this', 'b) super', 'c) self'], correctAnswer: 'a) this', explanation: 'this pointer points to current object.', companyTag: 'Accenture' },
  { question: 'Which type of memory is volatile?', options: ['a) ROM', 'b) RAM', 'c) Hard Disk'], correctAnswer: 'b) RAM', explanation: 'RAM loses data when power is turned off.', companyTag: 'Accenture' },
  { question: 'What does ACID stand for in databases?', options: ['a) Atomicity, Consistency, Isolation, Durability', 'b) Accuracy, Clarity, Integrity, Durability', 'c) None'], correctAnswer: 'a) Atomicity, Consistency, Isolation, Durability', explanation: 'ACID ensures reliable DB transactions.', companyTag: 'Accenture' },

];

const codingData = [
 { "title": "Reverse a String", "description": "Reverse a given string.", "examples": [{ "input": "hello", "output": "olleh" }], "testCases": [{ "input": "hello", "output": "olleh" }, { "input": "world", "output": "dlrow" }], "companyTag": "TCS" },
  { "title": "Find Duplicate Elements in Array", "description": "Find and return all duplicate elements from the array.", "examples": [{ "input": "[1,2,2,3,4,4,5]", "output": "[2,4]" }], "testCases": [{ "input": "[1,2,2,3,3,4]", "output": "[2,3]" }, { "input": "[1,2,3,4]", "output": "[]" }], "companyTag": "TCS" },
  { "title": "Rotate an Array", "description": "Rotate an array by k positions.", "examples": [{ "input": "arr=[1,2,3,4,5], k=2", "output": "[4,5,1,2,3]" }], "testCases": [{ "input": "arr=[1,2,3,4,5], k=2", "output": "[4,5,1,2,3]" }, { "input": "arr=[10,20,30], k=1", "output": "[30,10,20]" }], "companyTag": "TCS" },
  { "title": "Check Palindrome String", "description": "Check if the given string is palindrome.", "examples": [{ "input": "madam", "output": "True" }], "testCases": [{ "input": "racecar", "output": "True" }, { "input": "hello", "output": "False" }], "companyTag": "TCS" },
  { "title": "Merge Two Sorted Arrays", "description": "Merge two sorted arrays into a single sorted array.", "examples": [{ "input": "[1,3,5],[2,4,6]", "output": "[1,2,3,4,5,6]" }], "testCases": [{ "input": "[1,2],[3,4]", "output": "[1,2,3,4]" }], "companyTag": "TCS" },
  { "title": "Search Element in Array", "description": "Find the index of a given element in an array. Return -1 if not found.", "examples": [{ "input": "[1,2,3,4,5], 3", "output": "2" }], "testCases": [{ "input": "[6,7,8,9], 9", "output": "3" }, { "input": "[2,4,6], 5", "output": "-1" }], "companyTag": "TCS" },
  { "title": "Sort Characters in String", "description": "Sort all characters in a string in alphabetical order.", "examples": [{ "input": "dcba", "output": "abcd" }], "testCases": [{ "input": "bca", "output": "abc" }, { "input": "xyz", "output": "xyz" }], "companyTag": "TCS" },
  { "title": "Find Second Largest Element in Array", "description": "Return the second largest element of an array.", "examples": [{ "input": "[1,2,3,4,5]", "output": "4" }], "testCases": [{ "input": "[10,20,30]", "output": "20" }, { "input": "[5]", "output": "-1" }], "companyTag": "TCS" },
  { "title": "Count Vowels in String", "description": "Count and return the number of vowels in the input string.", "examples": [{ "input": "apple", "output": "2" }], "testCases": [{ "input": "banana", "output": "3" }, { "input": "rhythm", "output": "0" }], "companyTag": "TCS" },
  { "title": "Balanced Parentheses", "description": "Check if parentheses in a string are balanced.", "examples": [{ "input": "()[]{}", "output": "True" }], "testCases": [{ "input": "([)]", "output": "False" }, { "input": "{[()]}", "output": "True" }], "companyTag": "TCS" },
  { "title": "Array Reversal", "description": "Reverse an array of integers.", "examples": [{ "input": "[1,2,3]", "output": "[3,2,1]" }], "testCases": [{ "input": "[4,5,6]", "output": "[6,5,4]" }], "companyTag": "Infosys" },
  { "title": "String Palindrome Check", "description": "Check if a string is palindrome.", "examples": [{ "input": "level", "output": "True" }], "testCases": [{ "input": "test", "output": "False" }], "companyTag": "Infosys" },
  { "title": "Array Rotation", "description": "Rotate array to the right by k steps.", "examples": [{ "input": "[1,2,3,4], k=2", "output": "[3,4,1,2]" }], "testCases": [{ "input": "[10,20,30,40], k=1", "output": "[40,10,20,30]" }], "companyTag": "Infosys" },
  { "title": "Find Substring Occurrences", "description": "Find all start indices of a substring in a string.", "examples": [{ "input": "ababcab, ab", "output": "[0,3]" }], "testCases": [{ "input": "hellohello, lo", "output": "[3,8]" }], "companyTag": "Infosys" },
  { "title": "Check Anagram Strings", "description": "Check if two strings are anagrams of each other.", "examples": [{ "input": "listen, silent", "output": "True" }], "testCases": [{ "input": "triangle, integral", "output": "True" }, { "input": "hello, world", "output": "False" }], "companyTag": "Infosys" },
  { "title": "Reverse a Singly Linked List", "description": "Reverse a singly linked list and return the head.", "examples": [{ "input": "1->2->3", "output": "3->2->1" }], "testCases": [{ "input": "10->20->30", "output": "30->20->10" }], "companyTag": "Infosys" },
  { "title": "Detect Cycle in Linked List", "description": "Return True if linked list has a cycle.", "examples": [{ "input": "1->2->3->2", "output": "True" }], "testCases": [{ "input": "1->2->3", "output": "False" }], "companyTag": "Infosys" },
  { "title": "Merge Two Sorted Linked Lists", "description": "Merge two sorted linked lists and return head.", "examples": [{ "input": "1->3, 2->4", "output": "1->2->3->4" }], "testCases": [{ "input": "5->7, 6->8", "output": "5->6->7->8" }], "companyTag": "Infosys" },
  { "title": "Count Character Frequency", "description": "Return the frequency of each character in a string.", "examples": [{ "input": "aabbbc", "output": "{'a':2,'b':3,'c':1}" }], "testCases": [{ "input": "xyzzyx", "output": "{'x':2,'y':2,'z':2}" }], "companyTag": "Infosys" },
  { "title": "Find Missing Number in Array", "description": "Find the missing number in a sequence from 1-N.", "examples": [{ "input": "[1,2,4,5]", "output": "3" }], "testCases": [{ "input": "[2,3,1,5]", "output": "4" }], "companyTag": "Infosys" },
  { "title": "Reverse a String", "description": "Reverse the input string.", "examples": [{ "input": "Wipro", "output": "orpiW" }], "testCases": [{ "input": "place", "output": "ecalp" }], "companyTag": "Wipro" },
  { "title": "Find Factorial", "description": "Find the factorial of the given number.", "examples": [{ "input": "5", "output": "120" }], "testCases": [{ "input": "3", "output": "6" }], "companyTag": "Wipro" },
  { "title": "Left Rotate Array", "description": "Rotate array to left by d positions.", "examples": [{ "input": "[1,2,3,4,5],d=2", "output": "[3,4,5,1,2]" }], "testCases": [{ "input": "[10,20,30],d=1", "output": "[20,30,10]" }], "companyTag": "Wipro" },
  { "title": "Check String Palindrome", "description": "Return True if the string is palindrome.", "examples": [{ "input": "refer", "output": "True" }], "testCases": [{ "input": "abcd", "output": "False" }], "companyTag": "Wipro" },
  { "title": "Find Largest Element in Array", "description": "Find the largest element in the given array.", "examples": [{ "input": "[1,6,2,3]", "output": "6" }], "testCases": [{ "input": "[9,8,7]", "output": "9" }], "companyTag": "Wipro" },
  { "title": "Count Even and Odd in Array", "description": "Count number of even and odd elements.", "examples": [{ "input": "[1,2,3,4]", "output": "{even:2,odd:2}" }], "testCases": [{ "input": "[2,4,6]", "output": "{even:3,odd:0}" }], "companyTag": "Wipro" },
  { "title": "Sum of Array Elements", "description": "Return sum of all elements in the array.", "examples": [{ "input": "[1,2,3]", "output": "6" }], "testCases": [{ "input": "[5,5,5]", "output": "15" }], "companyTag": "Wipro" },
  { "title": "Find Common Elements", "description": "Return common elements between two arrays.", "examples": [{ "input": "[1,2,3],[2,3,4]", "output": "[2,3]" }], "testCases": [{ "input": "[1,5,6],[6,1]", "output": "[1,6]" }], "companyTag": "Wipro" },
  { "title": "Reverse Linked List", "description": "Reverse singly linked list and return head.", "examples": [{ "input": "1->2->3", "output": "3->2->1" }], "testCases": [{ "input": "5->7", "output": "7->5" }], "companyTag": "Wipro" },
  { "title": "GCD of Two Numbers", "description": "Find the GCD of two numbers.", "examples": [{ "input": "20 30", "output": "10" }], "testCases": [{ "input": "15 25", "output": "5" }], "companyTag": "Wipro" },
  { "title": "Rotate Array", "description": "Rotate array by k positions.", "examples": [{ "input": "[1,2,3,4,5],k=2", "output": "[4,5,1,2,3]" }], "testCases": [{ "input": "[8,9,10],k=1", "output": "[10,8,9]" }], "companyTag": "Cognizant" },
  { "title": "Largest Element in Array", "description": "Return the largest element in array.", "examples": [{ "input": "[1,5,3,4,2]", "output": "5" }], "testCases": [{ "input": "[2,4,8,6]", "output": "8" }], "companyTag": "Cognizant" },
  { "title": "Find Second Largest Element", "description": "Return second largest in array.", "examples": [{ "input": "[7,8,3,5]", "output": "7" }], "testCases": [{ "input": "[10,20,30]", "output": "20" }], "companyTag": "Cognizant" },
  { "title": "Find Palindromic Array", "description": "Check if array is palindromic.", "examples": [{ "input": "[1,2,1]", "output": "True" }], "testCases": [{ "input": "[4,5,6]", "output": "False" }], "companyTag": "Cognizant" },
  { "title": "Element with Left Smaller and Right Greater", "description": "Find elements with left smaller and right greater.", "examples": [{ "input": "[1,2,3,4,5]", "output": "[2,3,4]" }], "testCases": [{ "input": "[5,4,3]", "output": "[]" }], "companyTag": "Cognizant" },
  { "title": "Missing Number in Array", "description": "Find missing number from 1 to N.", "examples": [{ "input": "[1,3,4]", "output": "2" }], "testCases": [{ "input": "[2,4,1]", "output": "3" }], "companyTag": "Cognizant" },
  { "title": "Count Zeros in Array", "description": "Count number of zeros in array.", "examples": [{ "input": "[0,1,0,2,0]", "output": "3" }], "testCases": [{ "input": "[1,2,3]", "output": "0" }], "companyTag": "Cognizant" },
  { "title": "Print Alternate Elements", "description": "Print alternate elements from array.", "examples": [{ "input": "[1,2,3,4,5]", "output": "[1,3,5]" }], "testCases": [{ "input": "[2,4,6,8]", "output": "[2,6]" }], "companyTag": "Cognizant" },
  { "title": "Sum of Array Elements", "description": "Sum all elements in array.", "examples": [{ "input": "[2,4,6]", "output": "12" }], "testCases": [{ "input": "[5,5,5]", "output": "15" }], "companyTag": "Cognizant" },
  { "title": "Remove Duplicates from Array", "description": "Remove duplicate elements from array.", "examples": [{ "input": "[1,2,2,3,3]", "output": "[1,2,3]" }], "testCases": [{ "input": "[10,20,10]", "output": "[10,20]" }], "companyTag": "Cognizant" },
  { "title": "Find HCF (GCD) of Two Numbers", "description": "Find HCF of two numbers without recursion.", "examples": [{ "input": "70 15", "output": "5" }], "testCases": [{ "input": "24 36", "output": "12" }], "companyTag": "IBM" },
  { "title": "Proper String Compression", "description": "Given a string with characters and frequencies, decompress and sort by character.", "examples": [{ "input": "a3b5c2a2", "output": "aaabbbbbcc" }], "testCases": [{ "input": "x2y3x1", "output": "xxyyyx" }], "companyTag": "IBM" },
  { "title": "Palindrome Check", "description": "Check if string is palindrome using two pointers.", "examples": [{ "input": "radar", "output": "True" }], "testCases": [{ "input": "hello", "output": "False" }], "companyTag": "IBM" },
  { "title": "Sum Two Numbers", "description": "Sum two integers.", "examples": [{ "input": "7 8", "output": "15" }], "testCases": [{ "input": "5 6", "output": "11" }], "companyTag": "IBM" },
  { "title": "Find Factorial", "description": "Return factorial of n.", "examples": [{ "input": "4", "output": "24" }], "testCases": [{ "input": "6", "output": "720" }], "companyTag": "IBM" },
  { "title": "First Non-Repeating Character", "description": "Find first non-repeating character in string.", "examples": [{ "input": "swiss", "output": "w" }], "testCases": [{ "input": "success", "output": "u" }], "companyTag": "IBM" },
  { "title": "Binary Search", "description": "Search an element in a sorted array using binary search.", "examples": [{ "input": "[1,2,3,4,5], target=3", "output": "2" }], "testCases": [{ "input": "[10,20,30,40], target=20", "output": "1" }], "companyTag": "IBM" },
  { "title": "Fibonacci Number", "description": "Return nth Fibonacci number.", "examples": [{ "input": "5", "output": "5" }], "testCases": [{ "input": "10", "output": "55" }], "companyTag": "IBM" },
  { "title": "Check Prime Number", "description": "Return True if n is prime.", "examples": [{ "input": "7", "output": "True" }], "testCases": [{ "input": "8", "output": "False" }], "companyTag": "IBM" },
  { "title": "Reverse Words in String", "description": "Reverse words but not letters in string.", "examples": [{ "input": "hello world", "output": "world hello" }], "testCases": [{ "input": "abc def xyz", "output": "xyz def abc" }], "companyTag": "IBM" },
  { "title": "Binary String Operations", "description": "Given a binary string with AND, OR, XOR operations, compute the result.", "examples": [{ "input": "1C0C1C1A0B1", "output": "1" }], "testCases": [{ "input": "0C1A1B1C1C1B0A0", "output": "0" }], "companyTag": "Accenture" },
  { "title": "LargeSmallSum (Even/Odd Position)", "description": "Sum of second largest element in even positions and second smallest odd positions.", "examples": [{ "input": "[3,2,1,7,5,4]", "output": "7" }], "testCases": [{ "input": "[1,8,0,2,3,5,6]", "output": "8" }], "companyTag": "Accenture" },
  { "title": "Product of Smallest Pair", "description": "Find pair of two least elements whose sum ≤ target, return their product.", "examples": [{ "input": "sum=9, arr=[5,2,4,3,9,7,1]", "output": "2" }], "testCases": [{ "input": "sum=4, arr=[9,8,3,-7,3,9]", "output": "0" }], "companyTag": "Accenture" },
  { "title": "Sort an Array", "description": "Sort array of numbers.", "examples": [{ "input": "[3,1,4]", "output": "[1,3,4]" }], "testCases": [{ "input": "[5,2]", "output": "[2,5]" }], "companyTag": "Accenture" },
  { "title": "Check for Anagram", "description": "Return True if two strings are anagrams.", "examples": [{ "input": "note, tone", "output": "True" }], "testCases": [{ "input": "bat, tab", "output": "True" }], "companyTag": "Accenture" },
  { "title": "Reverse Linked List", "description": "Reverse a singly linked list.", "examples": [{ "input": "1->2->3", "output": "3->2->1" }], "testCases": [{ "input": "9->5->6", "output": "6->5->9" }], "companyTag": "Accenture" },
  { "title": "Find Max Subarray Sum", "description": "Longest continuous subarray sum.", "examples": [{ "input": "[1,-2,3,4,-1]", "output": "7" }], "testCases": [{ "input": "[2,4,-3,5]", "output": "8" }], "companyTag": "Accenture" },
  { "title": "Count Uppercase Characters", "description": "Count uppercase characters in string.", "examples": [{ "input": "AbcDE", "output": "3" }], "testCases": [{ "input": "aBc", "output": "1" }], "companyTag": "Accenture" },
  { "title": "Find Median Sorted Arrays", "description": "Find median of two sorted arrays.", "examples": [{ "input": "[1,2],[3,4]", "output": "2.5" }], "testCases": [{ "input": "[1],[2]", "output": "1.5" }], "companyTag": "Accenture" },
  { "title": "Check Rotation", "description": "Return True if one string is rotation of another.", "examples": [{ "input": "abcde, deabc", "output": "True" }], "testCases": [{ "input": "hello, llohe", "output": "True" }], "companyTag": "Accenture" },
  { "title": "Two Sum", "description": "Find indices of two numbers that add up to target in array.", "examples": [{ "input": "[2,7,11,15], target=9", "output": "[0,1]" }], "testCases": [{ "input": "[3,2,4], target=6", "output": "[1,2]" }], "companyTag": "" },
  { "title": "Reverse String", "description": "Reverse the characters of a string.", "examples": [{ "input": "hello", "output": "olleh" }], "testCases": [{ "input": "abc", "output": "cba" }], "companyTag": "" },
  { "title": "Merge Two Sorted Arrays", "description": "Merge two sorted arrays.", "examples": [{ "input": "[1,2,3],[2,5,6]", "output": "[1,2,2,3,5,6]" }], "testCases": [{ "input": "[1],[2]", "output": "[1,2]" }], "companyTag": "" },
  { "title": "Longest Substring Without Repeating Characters", "description": "Find the length of longest substring without repeating characters.", "examples": [{ "input": "abcabcbb", "output": "3" }], "testCases": [{ "input": "bbbbb", "output": "1" }], "companyTag": "" },
  { "title": "Binary Search", "description": "Use binary search to find element index in sorted array.", "examples": [{ "input": "[1,2,3,4,5], target=4", "output": "3" }], "testCases": [{ "input": "[6,7,8,9], target=6", "output": "0" }], "companyTag": "" },
  { "title": "Palindrome Linked List", "description": "Return True if linked list is palindrome.", "examples": [{ "input": "1->2->2->1", "output": "True" }], "testCases": [{ "input": "1->2", "output": "False" }], "companyTag": "" },
  { "title": "Remove Duplicates from Sorted Array", "description": "Remove duplicates in sorted array, return new length.", "examples": [{ "input": "[1,1,2]", "output": "2" }], "testCases": [{ "input": "[0,0,1,1,1,2,2,3,3,4]", "output": "5" }], "companyTag": "" },
  { "title": "Move Zeroes", "description": "Move all zeroes to end while maintaining order.", "examples": [{ "input": "[0,1,0,3,12]", "output": "[1,3,12,0,0]" }], "testCases": [{ "input": "[0,0,0,1]", "output": "[1,0,0,0]" }], "companyTag": "" },
  { "title": "Reverse Linked List", "description": "Reverse singly linked list.", "examples": [{ "input": "1->2->3", "output": "3->2->1" }], "testCases": [{ "input": "5->7", "output": "7->5" }], "companyTag": "" },
  { "title": "Find Min in Rotated Sorted Array", "description": "Find minimum element in rotated sorted array.", "examples": [{ "input": "[3,4,5,1,2]", "output": "1" }], "testCases": [{ "input": "[4,5,6,7,0,1,2]", "output": "0" }], "companyTag": "" },
  { "title": "Count and Say", "description": "Return nth term of 'Count and Say' sequence.", "examples": [{ "input": "4", "output": "1211" }], "testCases": [{ "input": "5", "output": "111221" }], "companyTag": "" },
  { "title": "Search Insert Position", "description": "Given sorted array and target, return index if found, else where it could be inserted.", "examples": [{ "input": "[1,3,5,6], target=5", "output": "2" }], "testCases": [{ "input": "[1,3,5,6], target=2", "output": "1" }], "companyTag": "" },
  { "title": "Find Peak Element", "description": "Find an index of a peak element.", "examples": [{ "input": "[1,2,3,1]", "output": "2" }], "testCases": [{ "input": "[1,2,1,3,5,6,4]", "output": "5" }], "companyTag": "" },
  { "title": "Intersection of Two Arrays", "description": "Return intersection of two arrays.", "examples": [{ "input": "[1,2,2,1],[2,2]", "output": "[2]" }], "testCases": [{ "input": "[4,9,5],[9,4,9,8,4]", "output": "[4,9]" }], "companyTag": "" },
  { "title": "Remove Nth Node From End of List", "description": "Given linked list, remove nth node from end.", "examples": [{ "input": "1->2->3->4->5, n=2", "output": "1->2->3->5" }], "testCases": [{ "input": "1->2, n=2", "output": "2" }], "companyTag": "" },
];

const interviewData = [
 { question: 'What is HTML?', type: 'technical', companyTag: 'TCS' },
  { question: 'What does DOCTYPE mean in HTML?', type: 'technical', companyTag: 'TCS' },
  { question: 'Explain the purpose of the <meta> tag.', type: 'technical', companyTag: 'Wipro' },
  { question: 'What is the difference between HTML and XHTML?', type: 'technical', companyTag: 'Accenture' },
  { question: 'What is semantic HTML?', type: 'technical', companyTag: '' },
  { question: 'Describe the difference between <div> and <span>.', type: 'technical', companyTag: 'Accenture' },
  { question: 'Explain the use of the <canvas> element.', type: 'technical', companyTag: 'Infosys' },
  { question: 'What are data attributes in HTML5?', type: 'technical', companyTag: 'Wipro' },
  { question: 'What is the purpose of the alt attribute in the <img> tag?', type: 'technical', companyTag: 'IBM' },
  { question: 'How do you create a hyperlink in HTML?', type: 'technical', companyTag: 'Wipro' },
  { question: 'What is the purpose of the <head> tag in HTML?', type: 'technical', companyTag: 'TCS' },
  { question: 'Explain the difference between <ol> and <ul> elements.', type: 'technical', companyTag: 'Cognizant' },
  { question: 'What is the significance of the lang attribute in HTML?', type: 'technical', companyTag: 'Infosys' },
  { question: 'What is the purpose of the <form> element in HTML?', type: 'technical', companyTag: 'TCS' },
  { question: 'How does the target attribute work in HTML forms?', type: 'technical', companyTag: 'Cognizant' },
  { question: 'What is CSS and what does it stand for?', type: 'technical', companyTag: 'Accenture' },
  { question: 'Explain the difference between inline, block, and inline-block elements.', type: 'technical', companyTag: '' },
  { question: 'Describe the box model in CSS.', type: 'technical', companyTag: 'Accenture' },
  { question: 'What is the purpose of the clear property in CSS?', type: 'technical', companyTag: 'TCS' },
  { question: 'Explain the difference between position: relative; and position: absolute;.', type: 'technical', companyTag: '' },
  { question: 'What is the CSS selector specificity and how is it calculated?', type: 'technical', companyTag: 'IBM' },
  { question: 'How can you center an element horizontally and vertically using CSS?', type: 'technical', companyTag: 'Infosys' },
  { question: 'Explain the purpose of the float property in CSS.', type: 'technical', companyTag: 'Wipro' },
  { question: 'Describe the difference between padding and margin.', type: 'technical', companyTag: 'Accenture' },
  { question: 'How does the display: none; property differ from visibility: hidden;?', type: 'technical', companyTag: 'Accenture' },
  { question: 'What is a CSS preprocessor, and why might you use one?', type: 'technical', companyTag: '' },
  { question: 'What is the "box-sizing" property in CSS?', type: 'technical', companyTag: 'Accenture' },
  { question: 'How do you include external stylesheets in HTML?', type: 'technical', companyTag: 'IBM' },
  { question: 'What is the difference between em and rem units in CSS?', type: 'technical', companyTag: 'Accenture' },
  { question: 'How does the z-index property work in CSS?', type: 'technical', companyTag: '' },
  { question: 'What is JavaScript?', type: 'technical', companyTag: '' },
  { question: 'Explain the difference between let, const, and var in JavaScript.', type: 'technical', companyTag: 'Accenture' },
  { question: 'Describe hoisting in JavaScript.', type: 'technical', companyTag: 'IBM' },
  { question: 'What is the purpose of the this keyword in JavaScript?', type: 'technical', companyTag: 'Cognizant' },
  { question: 'What are closures in JavaScript?', type: 'technical', companyTag: 'Cognizant' },
  { question: 'Explain the concept of prototypal inheritance in JavaScript.', type: 'technical', companyTag: 'Wipro' },
  { question: 'How does event delegation work in JavaScript?', type: 'technical', companyTag: 'TCS' },
  { question: 'Describe the difference between == and === in JavaScript.', type: 'technical', companyTag: 'IBM' },
  { question: 'What is the purpose of the async keyword in JavaScript?', type: 'technical', companyTag: 'Wipro' },
  { question: 'How do you handle errors in JavaScript?', type: 'technical', companyTag: '' },
  { question: 'Explain the concept of callback functions.', type: 'technical', companyTag: 'TCS' },
  { question: 'What is the difference between null and undefined in JavaScript?', type: 'technical', companyTag: 'IBM' },
  { question: 'Describe the role of the bind method in JavaScript.', type: 'technical', companyTag: 'TCS' },
  { question: 'What is the purpose of the map function in JavaScript?', type: 'technical', companyTag: '' },
  { question: 'Explain the concept of promises in JavaScript.', type: 'technical', companyTag: 'Infosys' },
  { question: 'What is the event loop in JavaScript?', type: 'technical', companyTag: 'Accenture' },
  { question: 'Describe the difference between null, undefined, and undeclared in JavaScript.', type: 'technical', companyTag: '' },
  { question: 'How do you create an object in JavaScript?', type: 'technical', companyTag: 'Cognizant' },
  { question: 'Explain the purpose of the localStorage and sessionStorage objects.', type: 'technical', companyTag: 'TCS' },
  { question: 'How does the typeof operator work in JavaScript?', type: 'technical', companyTag: 'TCS' },
  { question: 'How do you link a JavaScript file to an HTML file?', type: 'technical', companyTag: 'Infosys' },
  { question: 'What is the purpose of the defer attribute in a script tag?', type: 'technical', companyTag: '' },
  { question: 'Explain how to include an external CSS file in an HTML document.', type: 'technical', companyTag: 'Cognizant' },
  { question: 'What is the importance of the viewport meta tag in responsive design?', type: 'technical', companyTag: 'Cognizant' },
  { question: 'Describe the purpose of the @media rule in CSS.', type: 'technical', companyTag: 'IBM' },
  { question: 'How do you include external JavaScript libraries in your project?', type: 'technical', companyTag: 'Accenture' },
  { question: 'Explain the purpose of the <!DOCTYPE html> declaration in HTML5.', type: 'technical', companyTag: 'IBM' },
  { question: 'How can you optimize website performance using CSS and JavaScript?', type: 'technical', companyTag: 'Wipro' },
  { question: 'What is the purpose of the lang attribute in the <script> tag?', type: 'technical', companyTag: 'Infosys' },
  { question: 'How do you handle browser compatibility issues in CSS and JavaScript?', type: 'technical', companyTag: 'Accenture' },
  { question: 'What is responsive design?', type: 'technical', companyTag: 'Cognizant' },
  { question: 'Explain the difference between adaptive and responsive design.', type: 'technical', companyTag: 'Accenture' },
  { question: 'Describe the purpose of media queries in CSS.', type: 'technical', companyTag: 'Infosys' },
  { question: 'What is a CSS framework, and why might you use one?', type: 'technical', companyTag: '' },
  { question: 'How does a CSS grid system work in responsive design?', type: 'technical', companyTag: 'Wipro' },
  { question: 'Explain the concept of a mobile-first approach in web development.', type: 'technical', companyTag: '' },
  { question: 'What is the importance of the viewport meta tag in responsive design?', type: 'technical', companyTag: 'Cognizant' },
  { question: 'How can you make a website accessible to users with disabilities?', type: 'technical', companyTag: 'Infosys' },
  { question: 'What is the purpose of the rem unit in responsive design?', type: 'technical', companyTag: 'Cognizant' },
  { question: 'Explain the role of the max-width property in responsive design.', type: 'technical', companyTag: 'Cognizant' },
  { question: 'What is the DOM?', type: 'technical', companyTag: 'Infosys' },
  { question: 'How do you select elements with JavaScript in the DOM?', type: 'technical', companyTag: 'IBM' },
  { question: 'Explain the difference between innerHTML and textContent.', type: 'technical', companyTag: 'Infosys' },
  { question: 'How does event delegation work in JavaScript?', type: 'technical', companyTag: 'Accenture' },
  { question: 'What is the purpose of the addEventListener method?', type: 'technical', companyTag: '' },
  { question: 'How do you prevent the default behavior of an event in JavaScript?', type: 'technical', companyTag: 'Wipro' },
  { question: 'Describe the difference between the focus and blur events.', type: 'technical', companyTag: 'IBM' },
  { question: 'Explain the purpose of the event.stopPropagation() method.', type: 'technical', companyTag: 'Accenture' },
  { question: 'How can you dynamically create elements in the DOM with JavaScript?', type: 'technical', companyTag: 'Infosys' },
  { question: 'What is the purpose of the data-* attributes in HTML5?', type: 'technical', companyTag: 'TCS' },
  { question: 'What are the arrow functions in JavaScript?', type: 'technical', companyTag: 'TCS' },
  { question: 'Describe the let and const keywords introduced in ES6.', type: 'technical', companyTag: '' },
  { question: 'What is destructuring assignment in JavaScript?', type: 'technical', companyTag: 'TCS' },
  { question: 'Explain the purpose of the template literals in ES6.', type: 'technical', companyTag: 'Accenture' },
  { question: 'What are the let and const keywords in ES6?', type: 'technical', companyTag: 'Cognizant' },
  { question: 'How do you use the import and export statements in ES6?', type: 'technical', companyTag: 'TCS' },
  { question: 'What is the purpose of the spread operator (...) in JavaScript?', type: 'technical', companyTag: 'TCS' },
  { question: 'Describe the class syntax in ES6 and how it relates to object-oriented programming.', type: 'technical', companyTag: 'Cognizant' },
  { question: 'Explain the concept of promises and the async/await syntax in JavaScript.', type: 'technical', companyTag: 'Accenture' },
  { question: 'What are the rest parameters in JavaScript?', type: 'technical', companyTag: 'Wipro' },
  { question: 'How do you optimize the loading time of a web page?', type: 'technical', companyTag: '' },
  { question: 'Explain the concept of lazy loading in web development.', type: 'technical', companyTag: 'Infosys' },
  { question: 'What is the purpose of bundling and minification in web development?', type: 'technical', companyTag: '' },
  { question: 'How can you reduce the number of HTTP requests on a web page?', type: 'technical', companyTag: '' },
  { question: 'Describe the importance of using a content delivery network (CDN).', type: 'technical', companyTag: 'TCS' },
  { question: 'What is tree shaking in the context of JavaScript and bundling?', type: 'technical', companyTag: 'Wipro' },
  { question: 'Explain the difference between synchronous and asynchronous loading of scripts.', type: 'technical', companyTag: 'IBM' },
  { question: 'How can you optimize images for a web page?', type: 'technical', companyTag: 'Wipro' },
  { question: 'Describe the significance of using the rel="preload" attribute.', type: 'technical', companyTag: 'Infosys' },
  { question: 'What is the purpose of the "defer" attribute in a script tag, and how does it affect page loading?', type: 'technical', companyTag: 'Cognizant' },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connected for seeding');

    // Delete existing data
    await Mcq.deleteMany({});
    await CodingProblem.deleteMany({});
    await InterviewQuestion.deleteMany({});

    // Insert new data
    await Mcq.insertMany(mcqData);
    await CodingProblem.insertMany(codingData);
    await InterviewQuestion.insertMany(interviewData);

    console.log('Data seeded successfully');
  } catch (err) {
    console.error('Seeding error:', err.message);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    console.log('MongoDB disconnected');
  }
}

seed().catch((err) => {
  console.error('Seed process failed:', err.message);
  process.exit(1);
});